---
- name: Delete user on ASA
  hosts: asa
  gather_facts: no
  vars:
    asa_username_to_delete: "user_to_delete"
  tasks:
    - name: Delete user configuration
      ios_config:
        provider: "{{ cli }}"
        commands:
          - no username {{ asa_username_to_delete }}
          - privilege exec level 15 show running-config
      register: config_result

    - name: Display configuration changes
      debug:
        var: config_result.stdout_lines
